Fixcarousel
Job-Advisor-project/FrontEnd pull request #76
Opened 2022-11-21 01:12 UTC by minjupgeorge

## General Checks

- [ ] the branch is up to date with `main`/`master`
- [ ] the code works when pulled and run locally
- [ ] All CI checks pass
- [ ] all conflicts are resolved (if any)
- [ ] PR has a descriptive title
- [ ] PR has appropriate labels and milestones for easy identification
- [ ] PR it is assigned to the owner
- [ ] reviewers are assigned
- [ ] the PR contributes only one focused change
- [ ] It is in the appropriate column in the project board (if necessary)
- [ ] has short and clear description
- [ ] is linked to an issue (if it is related)
- [ ] feedback is addressed (if any and if it is appropriate feedback.)

## Markdown

- [ ] the markdown source is formatted
- [ ] spelling and grammar is correct in all text
- [ ] The markdown looks correct when you preview the file
- [ ] all links and images work

### HTML

- [ ] pages besides `/index.html` are stored in `/pages`
- [ ] the code is well-formatted
- [ ] the HTML is valid
- [ ] there are no inline styles (example: `style='color: red;'`)
- [ ] there are no `<style>` tags with CSS, all styles are hrefs
- [ ] there is no inline JavaScript (example: `onclick='doSomething()'`)
- [ ] there are no `<script>` tags with JS, all JS is in an separate file
- [ ] `id`s are used for JavaScript only, not for CSS
- [ ] semantic tags are used
- [ ] spelling and grammar is correct in all site content

### CSS

- [ ] the code is well-formatted
- [ ] passes all the linting checks

2022-11-21 08:40 UTC, MMikhailova requested changes
@minjupgeorge multiple cards look better, thank you. Can you please check the images, they are compressed. May be @FennyWilriani could help with it.

2022-11-21 13:02 UTC, MMikhailova approved these changes

2022-11-22 10:00 UTC, minjupgeorge commented
@MMikhailova Thanks for your valuable comments. I have loaded images from assets folder this time . Earlier it was url link. @FennyWilriani please look into the image size if possible

2022-11-22 12:09 UTC, FennyWilriani approved these changes

2022-11-22 12:10 UTC, merged